### ISSUE TITLE
[Suggestion] "Today" mappings option

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/ForgeGradle#216]
Perhaps add in an option to type "today" as your mappings and it will download snapshot_YYYYMMDD based on the current day (Hopefully same as the latest one on the mcp site) would make managing multiple projects easier as you could just "gradle setupDecompWorkspace eclipse" on the projects without even editing any files and the mappings would get updated.

**Comment by Lunatrius** [comment]
I'm against this. This will *break* projects if and of the mapping for methods/fields the project uses changes.

Instead I'd suggest to use a script to change the mappings in the properties file. I use [these 2 scripts](https://gist.github.com/437a0726d344bc7284c5) to update the mappings for all my projects at the same time (`updatemappings.sh snapshot_20150403`).

**Comment by 61352151511** [comment]
Well someone would go to build their mod and it would fail, then they could easily just open up eclipse/intellij or whatever they use, find what mappings are changed, and fix it, then build the mod. If someone has an automated build system set up they probably shouldn't use auto updating mappings, this is intended just to quickly update them for people who manually run "gradle setupDecompWorkspace eclipse"

**Comment by AbrarSyed** [comment]
im thinking "snapshots_latest" or "stable_latest" or some such.. ofcourse its people's own faults if they get compile errors because of it.

I should also mention that automatic source mapping updating is planned (as in update your mappings in your sources automatically).

**Comment by Lunatrius** [comment]
Instead of adding those aliases, why not add a task that will update the mappings version? Would have to limit it to an in-line string in the gradle file (and possibly a specific key in gradle.properties).

That way you'll always have the latest mappings and the pushed code won't break if anyone else tries to work on it at a later date.

**Comment by LexManos** [comment]
Sadly this one one that is HAS to be a no on. Making code dependant on the time/date of it being compiled is a horrible idea.
Just imagine, you want to compile IC2 from a year ago. But you can't because who knows what mapping it was actually built for there would be thousands of errors.
Yes this idea may sound good but the implications are definitely not worth it. 
Normal dependencies can be updated minorly in the backend without problem as long as the API stays the same. However these mapping explicitly BREAK the api so silent updating is a horrible idea.
