### ISSUE TITLE
Build errors in certain scenarios until running setupDecompWorkspace once

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/ForgeGradle#226]
I've brought up this issue quite some time on IRC before, but kind of forgot to keep track. The issue still exists, apparently: when building my mod on a machine without running `setupDecompWorkspace` at least once, the build will error out with the following:
```
li/cil/oc/client/renderer/tileentity/RobotRenderer.scala:392: type mismatch;
found   : net.minecraft.client.renderer.block.model.ItemCameraTransforms.TransformType(THIRD_PERSON)
required: net.minecraft.client.renderer.block.model.net.minecraft.client.renderer.block.model.
           itemRenderer.renderItem(Minecraft.getMinecraft.thePlayer, stack, TransformType.THIRD_PERSON)
```

Tested with 1.8-11.14.1.1354 and 11.14.2.1430. A full `--stacktrace --debug` log [can be found here](https://gist.githubusercontent.com/fnuecke/0e36e20ff4b32fbe0680/raw/build.log).

I can reproduce this reliably on different systems (Windows, different Linux distros), as long as `sDecW` has *not* been run on that machine before. To reproduce, clone the [`master-MC1.8` branch of my repo](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.8) and run `gradlew build` on a "fresh" machine.

I forgot about it, because as mentioned, it works fine after running `sDecW` once, so that's an acceptable workaround for me, but when someone unaware of this tries to compile the mod... well.

**Comment by LexManos** [comment]
I'll look into it, if i remember correctly this is scala being broken and relying on something that isn't in the class format specs. 
As you can see its not detecting he signature of that method correctly and prepending the package twice.

**Comment by Mumfrey** [comment]
Shouldn't affect mixins, they don't make any assumptions like that and the AP gets most of the relevant info it needs from the compiler itself at compile time. I certainly don't rely on anything which is outside either the class format specs or the compiler specs.

If I get a spare second I'll try out the new MCInjector but I don't forsee this being a problem. Even if it is, I'll fix it on my end.

**Comment by LexManos** [comment]
Was just worried that having to 'guess' the access may cause issues with your compiling/mixing of the inner class attributes when it runs into say a class that SHOULD be a enum but because we don't have that context it's just a normal public.

**Comment by Mumfrey** [comment]
No that shouldn't affect me because mixins don't care too much about the actual disposition of their target when mixing/obfuscating. All they actually care about is:

* Class hierarchy (this is immutable, so always good)
* Target is not an interface (again, pretty deterministic)
* Shadowed stuff in the mixin exists in the target (basically immutable)

Whether the target is an inner class or whatever is basically ignored/left alone, mixins deliberately don't support inner classes because the synthetic shit they create is just too much of a headache for not enough actual usefulness.

Similarly, at compile time all the AP cares about is

* class exists
* entries can be found the SRG file for fields in the target class

Again, everything which is not relevant is ignored. Visibility of the class is again pretty much irrelevant.

So yeah, go nuts. It shouldn't affect mixins at all because they largely don't care about class attributes.

**Comment by LexManos** [comment]
Alright we tested out his mod in a fresh VM, compiles fine with new MCInjector so closing.

**Comment by fnuecke** [comment]
Can confirm, thanks for the quick fix!

Just a note if anyone else had this issue, in addition to `--refresh-dependencies` I also needed to do a `clean` on the machine I tested it before.
