### ISSUE TITLE
FG doesn't decompile correctly in some cases

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/ForgeGradle#260]
https://github.com/ModCoderPack/MCPBot-Issues/issues/31
https://travis-ci.org/TechShroom/TBMRebooted/builds/79224219#L156

I have no clue as to what causes this, and it only happens on Travis-CI for me. A `setupCIWorkspace` on my side produces no such errors. MCP says it's not a mapping problem, so I imagine it's FG.

**Comment by AbrarSyed** [comment]
Seems like a generic issue.. Comparable<Object> shouldnt be a thing.. should be properly typecasted with the generics.. hmm...

**Comment by matthewprenger** [comment]
IIRC 53118683683dec2541fbb9fd8fead3b3e4d66408 was what fixed this before. I had the same problems with CommandBase.

**Comment by AbrarSyed** [comment]
Actually.. it was because I was an idiot and was applying the wrong EXC file. The exceptor/McInjector is whats supposed to fix the generics and exceptions and stuff, and I was accidentally using the wrong config and thus everything was weird. The code added in that commit no longer exists because I fixed the problem by using the correct EXC file...

Either way.. it seems to be the opposite issue now.. Instead of existing when it wasnt wanted.. its now missing when its needed...

**Comment by matthewprenger** [comment]
Just ran into this problem myself. A subclass of `CommandBase` fails to compile:
```
error: CommandSilence is not abstract and does not override abstract method compareTo(Object) in Comparable
```
The line in `CommandBase`:
```java
public int compareTo(Object p_compareTo_1_)
{
    return this.compareTo((ICommand)p_compareTo_1_);
}
```
This does only happen on the CI/dev setups, not decomp.

**Comment by robin4002** [comment]
I have the same problem with ForgeGradle 2 and the command from my mod (same error on the method compareTo when I compile after using setupCIWorkspace). If I compile after using setupDecompWorkspace there is no problem.

**Comment by AbrarSyed** [comment]
5b343996cbf0c7d38bfa7deac14dc7971455a789
try the latest snapshot..

**Comment by robin4002** [comment]
Work for me, after a clean of gradle and setupCIWorkspace. Thanks :)

**Comment by liach** [comment]
I thought that was an issue with generics... Thanks.
