### ISSUE TITLE
Allow for per-project dependency folders in gradle cache

### ISSUE THREAD

**Issue by gabizou** [MinecraftForge/ForgeGradle#270]
I've arrived at a problem today as I started developing another forge project, except this one uses FG2 (as recommended), and for some reason, FG2 couldn't resolve any of the dev dependencies, so the first instinct was to tell IntelliJ to refresh the gradle project, then close IntelliJ, run `gradle clean`, run `gradle setupDecomWorkspace`, and re-import the project to IntelliJ. It still could not resolve certain dependencies. My last resort, as most everyone else's, is to run `gradle cleanCache` and then `gradle setupDecompWorkspace` again.

This is where the unexpected happened, I already have two other FG projects, and those depend on a different version of Forge, and another one that depends on an entirely different version of MC with Forge. What ended up happening was that all of the forge bins were gone, requiring each and every one of those projects to also run `gradle setupDecompWorkspace` and refresh, if not reimport into IntelliJ.

It should be well possible to separate dependencies out to separate folders such that one project's `cleanCache` doesn't affect every other project on the filesystem.

Yes, this is more of a "gotcha!" type of issue, but it's still something that very well shouldn't happen unexpectedly in the first place.

**Comment by Cazzar** [comment]
Generally the dependencies are re-computed at runtime for ForgeGradle and
whilst you shouldn't need to run gradle clean and especially not cleanCache
to switch projects.. Maybe there's an underlying problem here?

Though there are multiple ways that you can move ~/.gradle (aka the global
one) from its default location, IIRC one way is GRADLE_USER_HOME

**Comment by gabizou** [comment]
Yes, generally, I shouldn't need to run clean or cleanCache, but today I had to update my workspace for one project from FG1.2 to FG2, and even though I nuked the IntelliJ stuff, gradle was still referencing some older jar, and the only way to fix it was unfortunately to use cleanCache, and that's when I learned that all projects would need to setupDecompWorkspace all over again.

**Comment by Cazzar** [comment]
Well, as mentioned before you can already move the gradle home with gradle
itself, see:
https://docs.gradle.org/current/userguide/gradle_command_line.html

**Comment by AbrarSyed** [comment]
The cache is only used for files that can be common between projects. If there are multiple projects that have different MC versions, thats fine, and they probably wont share any files. However if there are no ATs used, they will all still be stored in the global cache.

CleanCache is exactly what it sounds like, cleans the entire cache. It makes perfect sense that every project had to be re-setup after cleaning the global cache. This is in fact the main reason we discourage using CleanCache except as a last resort in the first place. This has been how ForgeGradle was designed from the very beginning.

As for a per-project dependency cache... FG2 already stores the minecraft jars and stuff (if you use an AT) in `project/.gradle/minecraft `. This was moved from project/build because people complained that they had to do the setupDecompWorkspace every time they ran clean. the `project/.gradle/minecraft` folder is also deleted when you run cleanCache.

Im not sure what went wrong with your setup, running with a --refresh-dependencies may have fixed it. I guess you could call it a gotcha, but its been the case even in FG 1.2.

**Comment by gabizou** [comment]
While I 100% understand the reasoning as you've mentioned, would it be possible otherwise to have an fg option for the project's build.gradle? I can imagine that that type of feature would be added on an exhaustive todo list and likely get finished in months from now, but still, it would be a feature that I'm sure some projects/developers would be able to say "I have enough space, I don't mind the extra redundancy."

**Comment by LexManos** [comment]
The simple answer is no, it's not needed.
1) You can do it using built in gradle features so why duplicate it?
2) cleanCache is MEANT to be catastrophic and destroy everything, you shouldn't use it unless shit is SEVERELY broken. Re-running setup for every project is an INTENDED result.
