### ISSUE TITLE
Code style support in project for Eclipse - config file is changed during "gradle eclipse"

### ISSUE THREAD

**Issue by the-vindex** [MinecraftForge/ForgeGradle#318]
# Context
I'm setting up preconfigured code style (code formatting, spaces vs tabs, curly braces etc.) for a project.
Eclipse allows this to be done by comitting to source control .settings/ folder with org.eclipse.jdt.core.prefs and org.eclipse.jdt.ui.prefs. When developer then runs gradle eclipse and loads the project into Eclipse, he has all formatting preconfigured and when he commits changes, code formatting actually matches project rules. We should agree this is a good thing ;-)

# Issue
Now this works ok, except one thing - when I run gradle eclipse for such setup:
1) file .settings/org.eclipse.jdt.core.prefs is sorted differently than Eclipse has saved it
2) sorting is not stable accross individual runs (some lines gets different order on different runs)
3) 2 lines of text are added at the beginning:
#
#Fri Jan 01 08:46:23 CET 2016

This causes this file to be always modified in local development environment each time developer has to run gradle eclipse.
Please, ensure points 2 and 3 don't happen.
Point 1 is fine as long as it happens only once, then I can commit the file to repo and forget about it.

Example files follow:
[.settings.zip](https://github.com/MinecraftForge/ForgeGradle/files/75870/default.settings.zip)

**Comment by AbrarSyed** [comment]
I bet thats eclipse making those changes...
regardless, I have no control over that, the eclipse task is a builtin gradle thing.

I also recommend you use a different way to manage formatting, like the gradle checkstyle. You can also export the eclipse formatting XML so that contributors can import it instead of keeping IDE specific code in your repository. Dont forget about intellij users...
