### ISSUE TITLE
Let tweakers use patcher tasks

### ISSUE THREAD

**Issue by Guichaguri** [MinecraftForge/ForgeGradle#395]
Binary patches can be really useful for tweakers (Forge itself uses them). The tasks for applying Java patches, compiling them and then generating binary patches already exist in ForgeGradle.
I don't know much about how gradle tasks work, but I think adding them to tweaker-client and tweaker-server is probably easy

**Comment by killjoy1221** [comment]
AFAIK, you can't have multiple patcher mods on at once. Forge should probably be the only mod to use them (except maybe optifine).

You can just apply the patcher plugin anyway.

_Patch responsibly_

**Comment by Guichaguri** [comment]
@killjoy1221 Yes, you're right, XDelta can't patch the same file twice, but Badiff can.
[Badiff](http://badiff.org/wiki/Badiff) is a pretty fast O(ND) algorithm implementation written entirely in Java

I agree that only mods which require a lot of patching (not only a few hooks) should use binary patches. In my case, I need to recode a method but Forge adds a hook on it. If I patched using Badiff, everything would've worked without any issues

The patcher plugin is a great option, but it uses XDelta which could lead into conflicts as previously said.
Thanks for the suggestion :)

So should ForgeGradle change the binary patch library to Badiff or at least add an option for it?

**Comment by AbrarSyed** [comment]
I dont think simply changing the diff/patch algorithm is gonna do it here. There is also the problem of what you are generating patches off of. Generating a set of binary patches is only useful when you have a known starting point. In the case of Forge and FML, thats base MC. In the case of McEdu and Cauldron (of back in the day), this was ALSO MC, its just that their binary patches also included all the changes required by forge. 

The ability to allow multiple patches in sequence magnifies this problem considerably. Are the authors of these mods expected to make a different patch set for every possible combination of preceding patches? ASM, being dynamic with IF statements and all that is definitely a better option than trying to compile it down to a static binary patchset.

Regarding the application of patches at runtime like forge does with a tweaker.. thats not FGs problem. Its code that you would write as part of your tweaker. You can probably just copy said code from forge and it would likely work.

I hope I understood your proposal correctly and have given a suitable response.

**Comment by Guichaguri** [comment]
Thanks for your response.

ASM is the best option for any type of coremod/tweaker indeed, but when you're dealing with a large amount of code, it becomes harder to write and maintain it.
Binary Patches are easier to write and maintain code as well as obfuscation, but as you already pointed out, I'll have to deal with conflicts

I'll research and rethink I want to do to make sure it will be the best option.
And if I decide that I really want to use binary patches, I can always fork ForgeGradle and modify it for personal use

**Comment by killjoy1221** [comment]
You should consider using mixins instead. You'll be able to do just about anything you can when patching.

**Comment by Guichaguri** [comment]
@killjoy1221 I've looked into Mixin before, but it's still not clear to me how mixins handle static methods/fields and how can I partially patch a method/field instead of completely replacing it.

**Comment by killjoy1221** [comment]
Hop on irc #spongedev. They can help you out. You can also use #liteloader
where Mixin use is encouraged.

**Comment by Mumfrey** [comment]
> @killjoy1221 I've looked into Mixin before, but it's still not clear to me how mixins handle static methods/fields and how can I partially patch a method instead of completely replacing it.

Because with Mixin you switch your thinking away from "patching" and move towards making subtle modifications to a method. There is a lot of power at your disposal provided by [Injectors](https://github.com/SpongePowered/Mixin/wiki/Advanced-Mixin-Usage---Callback-Injectors) which take the form of [plain Injectors](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/Inject.html), [Redirectors](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/Redirect.html), [Variable Modifers](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/ModifyVariable.html), [Argument Modifers](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/ModifyArg.html) and [Constant-Expression Redirectors](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/ModifyConstant.html)(which are pretty powerful - imagine being able to take any constant number or string, and replace it with a call to your custom method).

I have also written (and am still writing) [extensive documentation](https://github.com/SpongePowered/Mixin/wiki) which starts with the basics and progressively works up to more complex topics, and I go to great pains to make these articles very graphic so that you get a good grip on the core concepts.

Way back when we started to develop Sponge, we ruled out binpatches as a viable approach because they are *just too __brittle__*. Binpatches work okay when you're the only game in town (eg. Forge uses them because they're a quick, simple, effective route-to-market) but as mentioned above if more than one party tries to leverage them, you quickly run into issues with needing to make delta patches or include "upstream" changes in a "downstream" patch set. At the other end of the scale, ASM is complex to write, complex to maintain, and requires a high degree of skill to leverage effectively. What we see in practice is people using ASM in a very "brute force" kind of way, which is in many ways as bad as trying to binpatch.

With LiteLoader my philosophy was always to gently guide people away from raw ASM and get them to subclass and use the suite of reliable, reusable and robust transformers I provided. [Mixin](https://github.com/SpongePowered/Mixin) as a project takes that suite of transformers and presents it to the mod author in an extremely user-friendly manner where you just encode your desired transformations in a familiar substrate - namely Java files.

I should say right now that Mixin is only a viable product thanks to ForgeGradle itself, and in particular support I received from @AbrarSyed in guiding me to make the Annotation Processor which can leverage the ForgeGradle environment to provide obfuscation services. This is supplanted by [MixinGradle](https://github.com/SpongePowered/MixinGradle/) which acts to weave the Mixin AP and ForgeGradle together in a way which takes even more arduous boilerplate away from the developer.

The point I'm trying to make is that all this effort has been expended in order to try and make *scorched-earth* approaches like binpatches and ham-fisted ASM nuke-it-from-orbit strategies not just less appealing but to try and remove the need for them altogether.

If you have questions about how you can use Mixins, please feel free to use `#spongedev` or `#liteloader` on esper. I am online when my nickname has an uppercase `M`.
