### ISSUE TITLE
Can't run on 32bit systems

### ISSUE THREAD

**Issue by 7osCraft** [MinecraftForge/ForgeGradle#418]
Hello,
So some people like me can't run 64bit OSes on their device because of drivers and stuff like that, but the problem is ForgeGradle 2.2 requires 3GB of memory to decompile minecraft, because of this we can't develop a mod.
So is there a way that we can change the 3GB to be 1GB or just use an old version of ForgeGradle or what?
Thanks

**Comment by AbrarSyed** [comment]
FG requires so much ram because the decompiler we used loads a lot of stuff into RAM. Also Minecraft has quote a lot of code in it, its not surprising that it takes so much RAM when decompiling. So no, sorry, there is no way for us to magically reduce the RAM consumption.

However, you can still develop if yo uuse `setupDevWorkspace` instead of `setupDecompWorkspace`. The dev workspace just deobfuscates MC, it doesnt decompile, so you should be able to get away with less ram. Though you will have to live and mod without being able to see the MC source code.

**Comment by spikespaz** [comment]
I'm thinking that if you can't get a 64 bit OS then it's just a wee-bit time to obtain a new computer.
Some things just cant be done on shitty hardware. This is one of those things. Like @AbrarSyed said though, use the dev environment and you can scrape by.
