### ISSUE TITLE
Release new versions to gradlePluginPortal

### ISSUE THREAD

**Issue by LeafHacker** [MinecraftForge/ForgeGradle#438]
Currently the [GitHub Releases] and [gradlePluginPortal] show the latest version as 2.0.2. This means that #197 has regressed. If you have CI setup to deploy to GH Releases and the gradle portal it may be configured to only deploy when a commit is tagged with a version number.

This would make it much more convenient to use gradle's DSL plugin syntax:

```gradle
plugins {
    id 'java'
    id 'net.minecraftforge.gradle.tweaker-client' version '2.3'
}
```

[GitHub Releases]: https://github.com/MinecraftForge/ForgeGradle/releases
[gradlePluginPortal]: https://plugins.gradle.org/search?term=minecraftforge

**Comment by CommanderTvis** [comment]
Why is so an important issue closed silently?

**Comment by LexManos** [comment]
1) Because it's old
2) Because it's NOT important
3) Because we don't care. We don't release on the plugin portal. We have our own release system that works fine without having to deal with the dumb stuff gradle's portal puts us through.
4) Because explaining why we say no to people tends to just open up the door for arguing which we don't want.
