### ISSUE TITLE
merged_at.cfg not found with 1.7.10 and FG 2.0.2

### ISSUE THREAD

**Issue by sorenbug** [MinecraftForge/ForgeGradle#477]
build.gradle:

```
buildscript {
    repositories {
        jcenter()
        maven {
            name = "forge"
            url = "https://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:2.0.2"
    }
}

apply plugin: "net.minecraftforge.gradle.forge"

version = modVersion
group = modGroup
archivesBaseName = modBaseName

minecraft {
    version = project.forgeVersion
    runDir = "run"

    // the mappings can be changed at any time, and must be in the following format.
    // snapshot_YYYYMMDD   snapshot are built nightly.
    // stable_#            stables are built at the discretion of the MCP team.
    // Use non-default mappings at your own risk. they may not always work.
    // simply re-run your setup task after changing the mappings to update your workspace.
    mappings = project.mcpVersion
    // makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.
}

repositories {
    mavenCentral()
}

dependencies {
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"

        // replace version and mcversion
        expand "version": project.version, "mcversion": project.minecraft.version
    }

    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}
```

gradle.properties:

```
modGroup=com.tsunderebug
modVersion=1.0-SNAPSHOT
modBaseName=Fizz
forgeVersion=10.13.4.1614-1.7.10
mcpVersion=stable_12
```

Error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deobfMcSRG'.
> java.io.FileNotFoundException: C:\Users\aprim\.gradle\caches\minecraft\net\minecraftforge\forge\1.7.10-10.13.4.1614-1.7.10\userdev\merged_at.cfg (The system cannot find the file specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Run with --stacktrace and --debug: [Hastebin Log](https://hastebin.com/ihohokozif.pl)

**Comment by jriwanek** [comment]
Use FG1.2, not 2.0.2

**Comment by tomasbrod** [comment]
Java 8 JDK
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "http://files.minecraftforge.net/maven"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
          url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT"
    }
}
apply plugin: 'forge'
```

**Comment by RareScrap** [comment]
FG1.2 cant use `useDepAts = true`. So question still open.

**Comment by DaemonUmbra** [comment]
1.7.10 is ancient so this is probably a wontfix

**Comment by Unnoen** [comment]
Forge currently only supports 1.12.2 and 1.14.4. Update.

**Comment by 0xilly** [comment]
1.7.10 and FG 2.2 are unsupported

**Comment by RareScrap** [comment]
Anyway 1.7.10 still live in Russia. This is a fact, deal with it. Propably sollution - write standalone gradle task with usage [Access Transformers methods](https://forgegradle.readthedocs.io/en/latest/reference/mcblock/) from minecraft{} script block.

**Comment by loordgek** [comment]
windows XP is also used but that doesn't mean you get support for it 
https://howoldisminecraft1710.today/

**Comment by RareScrap** [comment]
I experimented with FG1.2 and found that you can apply ATs with several calls of at() method in minecraft{} buld scrit block:
```gradle
minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "eclipse"
    at(file("$rootDir/test_at.cfg"))
    at(file("$rootDir/test1_at.cfg")) // Yea! This work.
}
```
Now I have no time to write a cycle, bypassing all dependencies. I think you understand the essence and can write it yourself.

Now let's talk about updates. At the moment, there is not yet a server that could support mods and plug-ins without a substantial increase in the minimum requirements. And I'm not the only one who thinks so. I know that there is an Sponge, but empirically I have determined that it requires much more memory. Moreover, I created 2 modpacks for 1.7.10 and 1.12.2 with the same mods (approximately 120 mods). With 50 players online, Sponzhe began to terribly slow down on my machine, while the old man 1.7.10 provides a comfortable game.

Do not forget about the fact that there is no guarantee that when you upgrade something will not break. I am not one of those people who want to constantly repair something. Moreover, I do not need content from the new versions.

And the most important thing is that I don’t want to spend a huge amount of time and effort on rewriting and testing my mods and plugins for 1.12.2 because some guys thinks that updates are a panacea for all problems. So answer me: WHAT FOR A REAL SENSITIVE BENEFIT WILL I GET FROM UPDATE?

Guys, do not repair things thats already works.

**Comment by LexManos** [comment]
Better rendering.
Better code.
Better content.
Better performance. {RAM is cheap, cpu is what matters}
Better libraries.
Better overall stability.
Better support.
Better community.
And the best benefit of updating. Not being an asshat who expects people to support your old shit because you're just to lazy to update and like to rationalize it to yourself.
The tools are in place to do whatever you want. We just arn't going to help you do it.
