### ISSUE TITLE
Reduction of JSON file sizes

### ISSUE THREAD

**Issue by samtrion** [MinecraftForge/ForgeGradle#507]
It would be nice if all JSON files are minimized during the build process before they are added to the package. This would have a positive effect on the file size of the .JAR files.

I realize that here we are talking about just a few percent of the total file size. But with constantly new JSON formats for BlockStates, Models, Recipes and so on, this gain is enormous, especially for the players.

**Comment by LexManos** [comment]
You can do that yourself, it will not be default in FG. Bandwidth and HD space is cheap, its better to keep things well formatted so people have a easier time reading them. This isn't like a web page where you're expected to be responsiveness in milliseconds and download the same thing thousands of times.

**Comment by covers1624** [comment]
Also, json files are text so zip (basically a jar file) would find them easily compressable, if I'm not mistaken.

**Comment by AbrarSyed** [comment]
You can do this in your build.gradle by adding code to the processResources{} task. Just parse it in with the JsonSlurper and spit it back out again without prety-printing.

Ref:
 - http://groovy-lang.org/json.html
- https://stackoverflow.com/questions/43111967/can-i-remove-some-lines-from-some-files-when-archiving-them-with-gradle

**Comment by Samtrion** [comment]
Here's an example: Direwolf20 1.12.2 2.0 Pack
Currently ships 143 mods with a total of 20,111 JSON files. These JSON files have a total size of 11,624,634 bytes.

If I minimize this I have a total size of 8,010,845 bytes. This corresponds to an approximate reduction of 30% of the file sizes.

So for a mid size modpack like this, we're talking about about 3.6 million bytes of data trash (spaces, line breaks, tabs). Which must be delivered, loaded and deserialized. The deserializer also has to interpret these bytes, so minimizing the JSON file size would also increase performance in loading and deserializing the JSON files.

Especially when you consider that more and more settings are made via JSON. The number of JSON files will increase rather than decrease. Which is a very positive effect.

@LexManos  You're right, I could solve it for my 2-3 mods myself, but that's not even scratching the surface. That's why I've addressed it here because integrating into FG would serve everyone.

@covers1624  You're right, but 3.6 million bytes are still delivered.

@AbrarSyed That there is a solution for this, I am aware. See https://stackoverflow.com/a/41029113

**Comment by LexManos** [comment]
3.6 MILLION BYTES sounds impressive, until you understand what that actually is, 3.4 MB.
And you haven't talked about it in compressed format, which means you're probably looking at {according to Minecraft.jar's compression ratio, rounded up} 20% of that. So 0.6MB
As for the interpreter having to process that data, at the end of the day it comes down to a if (data == ' ') data++; Which is a grand total of at MOST 6 CPU operations. With a normal 3GHz processor. We're talking 0.018S, or 18 ms.

So, this is THE DEFINITION of not worth the cost in devtime, or readability.
