### ISSUE TITLE
IllegalStateException on Gradle Task: deobfMcSRG

### ISSUE THREAD

**Issue by doublehelix457** [MinecraftForge/ForgeGradle#539]
I've run setupDecompWorkspace and I get hit with this:

https://pastebin.com/RUJTUzjU

Here is my build.gradle:

https://pastebin.com/5PwbuyLA

Iv'e tried just about everything. --refresh-dependencies, cleared the cache, deleted the cache folder, deleted the .gradle and nothing seems to fix this. My imports have also broken. Im not sure what else to do at this point.

**Comment by 14mRh4X0r** [comment]
I helped debug. It was due to a version clash between the ASM in ForgeGradle and in (an old version of) the [Shadow plugin](https://imperceptiblethoughts.com/shadow/). While using an updated version of that specific plugin resolves the exception, the actual issue here is that ASM is included in the ForgeGradle jar without relocation.

**Comment by liach** [comment]
for now i guess we can use resolutionstrategy

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
