### ISSUE TITLE
[FG3] Deobf dependencies not resolved

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/ForgeGradle#571]
After adding a `deobf` dependency like this in my **build.gradle**:
```gradle
dependencies {
    minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}"

    deobf "mcp.mobius.waila:Hwyla:1.10.1-B53_1.13.2"
}
```

I get the following error when refreshing the Gradle project:
```text
Could not resolve: mcp.mobius.waila:Hwyla:1.10.1-B53_1.13.2_mapped_snapshot_20190308-1.13.1
```

Adding the same dependency as `compile` rather than `deobf` works without issue (apart from it still using SRG names).

**Comment by LexManos** [comment]
Next time please provide the report for that custom dependency so I can properly test. But this should fix it.

**Comment by Choonster** [comment]
Thanks for the fix, but I don't understand exactly you wanted me provide. Did you want a full reproduction, i.e. a full **build.gradle** that reproduces this problem?

**Comment by Choonster** [comment]
I don't think this is working. You can see a **build.gradle** file to reproduce this and the relevant logs [here](https://gist.github.com/Choonster/441ed47db1ce715674ca45b2ea51d151).

* I renamed the **~/.gradle** directory to ensure that it wasn't a cache issue.
* I downloaded a fresh MDK (1.13.2-25.0.85) and added Hwyla as a deobf dependency in **build.gradle**. This can be seen in the Gist.
* I imported the new project into IDEA. This is the first log in the Gist.
* The import finished with an error, so I refreshed the project in IDEA's Gradle window. This is the second log in the Gist.
* Just to be sure, I ran `.\gradlew --refresh-dependencies --debug`. This is the third log in the Gist, though it doesn't seem to mention Hwyla at all.

At the end of this, Hwyla still can't be resolved:
![image](https://user-images.githubusercontent.com/878073/54487054-f3b54f80-48e4-11e9-911a-4ed0ea391eb7.png)

**Comment by EdwinMindcraft** [comment]
Had the same issue, try adding a / at the end of your repo declaration
`maven { url = "http://dvs1.progwml6.com/files/maven" }`
becomes
`maven { url = "http://dvs1.progwml6.com/files/maven/" }`

**Comment by Choonster** [comment]
Thanks for the tip. Just adding a trailing slash to the repository URLs didn't work, but adding a trailing slash and changing the `tehnut.info` URL to `https://` got it working. [This](https://github.com/Choonster-Minecraft-Mods/TestMod3/blob/5fb7d9c15841a6b4ff6fb6a79c400c6641796a63/build.gradle#L74-L88) is what I ended up with.

It seems that using `http://` or not including the trailing slash results in a `301 Moved Permanently` redirect to the `https://` URL with the trailing slash, which Gradle handles without issue for a regular `compile` dependency, but ForgeGradle doesn't handle for a `deobf` dependency.

**Comment by TehNut** [comment]
I guess I'll have to update my readme

**Comment by LexManos** [comment]
Interesting. we bypass grades internal downloading for deobf reps and others. so well just need to support those redirects and missing slashes. Simple change, if anyone wants to get at it before I get to it sometime this week.

**Comment by skyjay1** [comment]
Sorry to re-open this thread, but I'm having the same issue no matter what I try -- adding "https", the trailing "/". I'm adding an obfuscated mod jar (since no deobf jar is available) as an optional dependency and it's not working like it has in previous ForgeGradle versions.

My `build.gradle` file is [here](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/blob/master-1.13.2/build.gradle) and I'm attempting to add Hwyla just like Choonster, but I keep getting a similar problem:  `Could not resolve: mcp.mobius.waila:Hwyla:1.10.1-B58_1.13.2_mapped_snapshot_20180921-1.13`. (See [this output](https://pastebin.com/zrCB3nCz))
Using `compile` instead of `deobf` adds the dependency but causes ClassNotFound errors on startup because the source jar is still obfuscated.

Any suggestions? There's probably something obvious I'm missing... Maybe I need to clean the gradle cache? Or switch permanently to IDEA?

Attached is the result of running `gradlew dependencies --refresh-dependencies --stacktrace` in case that helps
![image](https://user-images.githubusercontent.com/15920401/58453852-cf8e9f80-80d9-11e9-89f0-4683ea58bfeb.png)

**Comment by mezz** [comment]
@skyjay1 please open a new issue, most likely you are running into something else and it will not be visible in a closed issue here.
