### ISSUE TITLE
Question: Which License is true?

### ISSUE THREAD

**Issue by anatawa12** [MinecraftForge/ForgeGradle#632]
In the FG_1,2 branch, [LICENSE](https://github.com/MinecraftForge/ForgeGradle/blob/FG_1.2/LICENSE) file says that this software is released under LGPL 2.1 but [ForgeGradle-1.2-20190215.223950-303.pom](http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/1.2-SNAPSHOT/ForgeGradle-1.2-20190215.223950-303.pom) says EPL 1.0. which is the license for ForgeGradle 1.2?

**Comment by srs-bsns** [comment]
Looks like when FG was re-licenced in 2014 (https://github.com/MinecraftForge/ForgeGradle/commit/d57f4a22c9e554b21ef8c4812c95c8ef7550336b) there was an oversight about updating the licence in the configuration of the `uploadArchives` task in the build.gradle, which was then fixed in FG2 here: https://github.com/MinecraftForge/ForgeGradle/commit/85a3b579b5b4a9ffb35d52b4bc261b9e864364da

In any sense, the LGPL 2.1 licence in this repo, not the one in the POM, is the valid one.

**Comment by anatawa12** [comment]
@srs-bsns thank you
