### ISSUE TITLE
Enhancement: genIntellijRuns generate runs for all subprojects

### ISSUE THREAD

**Issue by RareScrap** [MinecraftForge/ForgeGradle#634]
Hello. I have a multiproject mod with 2 submods. And I need to run the game for each of the projects in order to test them separately. It would be very cool if genIntellijRuns generated launch configurations for each of the subprojects. Now I have to duplicate manually and rename.

In a word, it would be great if genIntellijRuns produced a similar result:
![ывфывфывфыв](https://user-images.githubusercontent.com/7997602/68770024-5ae7f700-0660-11ea-947a-b4bcdfb2b77a.png)

**Comment by thecodewarrior** [comment]
If you have the runs defined in your `minecraft {}` block in each subproject you should be able to add this to your root project to have them all generate at once:
```groovy
subprojects.each {
    genIntellijRuns.finalizedBy(it.genIntellijRuns)
}
```

You can also customize the configs like so:
```groovy
minecraft {
    runs {
        client {
            taskName 'Subproject 2: Electric Boogaloo'
            ideaModule 'rootname.submodulename.main' // FG still generates this with an underscore in `_main` instead of `.main`, so this should fix it

            mods {
                ...
            }
        }
        ...
    }
}
```

Edit: Having this as a built-in ForgeGradle behavior is overkill and inflexible. For instance, for my mod I need to have only one run config that all the projects run together on. (This isn't as simple as it sounds, which is why it took over a week to get the setup working)
