### ISSUE TITLE
I know it's pretty much obsolete, but...

### ISSUE THREAD

**Issue by ARoberts1975** [MinecraftForge/ForgeGradle#653]
I know Minecraft 1.7.10 is basically obsolete, but I have been trying to get a 1.12.2 modded server working with much difficulty (which is the only reason I still use 1.7.10).
I have been running into many of the same problems with trying to HEAD and GET files for 1.7.10 Gradle as well. Most of these issues have been answered with "upgrade your forge to 1.12 or 1.14", and no real resolution has been found.
Again, I can't seem to get a 1.12.2 server running, and the mods I use aren't available for higher versions, yet.
I did manage to get 1.7.10 somewhat working, but the HTTPS and missing files issue is still there.

**Comment by jriwanek** [comment]
You might wanna change that title to "obsolete" instead of "pretty much obsolete", the forge folk ended support for 1.7.10 long ago, and even for 1.12 recently, I'd also advise you walk away and close the issue, It's only gonna get closed anyway, and that'll atleast avoid you getting shouted at for asking for support for an unsupported version.

**Comment by ARoberts1975** [comment]
It's okay anyway. I figured out how to work around it. It took some playing around with different Gradle versions, and it's been about a week and a half since I started. Hopefully, soon I'll figure out the 1.12 server issues, or a later version will be suitable for me.
