### ISSUE TITLE
[FG3] Resources not loading on 1.12.2

### ISSUE THREAD

**Issue by DeflatedPickle** [MinecraftForge/ForgeGradle#717]
I updated a few of my 1.12 mods to ForgeGradle3 so the build process wouldn't have to change when I updated to newer Minecraft versions. However, resources have stopped being loaded, or at least can't be found from Minecraft. They *would* load on ForgeGradle2. My AT is still loaded, though.

**Comment by Yunus1903** [comment]
1.12 is not supported anymore

**Comment by DeflatedPickle** [comment]
The Forge MDK for 1.12 was updated to use FG3. Why would they do that if it's not supported and didn't wand bug reports?

**Comment by TheCurle** [comment]
For our benefit, not yours.

**Comment by FinnT730** [comment]
Because the 1.12 code base is old, and almost no one remembers the code for it.

And, Ats work in later versions.
Bug reports, yes, if it's critical and game breaking, other then that, there is not really a reason elect for it anymore

**Comment by LexManos** [comment]
It was updated so that it could function. It does not mean that it is supported or that we will help you fix bugs.
If you're on an old version, you are on your own.
**IF** it is a FG "bug" then it is on you to submit a reproduction and fix if you care enough.
Basically, we are not going to put major effort into old versions. If others in the community want to they can and PR it in. I did 1.12 to show people that it could be done.
