### ISSUE TITLE
FG 3.0.185 - NPE during imports

### ISSUE THREAD

**Issue by JTK222** [MinecraftForge/ForgeGradle#718]
With FG 3.0.185 and this commit  3bb06c70617a8f3dfd23975f48b7846fb84b0f07
I can no longer create any/update/reimport any workspaces.
Reverting FG to 3.0.184 fixes that issues.
Here is the log I got from my IDE https://gist.github.com/JTK222/bbbe10476aa0c7c50cd1bcda79e7ce01
Sadly I am not very knowledgeable about Gradle, therefore I have no Idea what might be causing this.

**Comment by LexManos** [comment]
That makes absolutely no sense. 
You're getting a NPE here: https://github.com/MinecraftForge/ForgeGradle/blob/097dd2a7145a3a4384ffa77876a55fe0b46b6551/src/userdev/java/net/minecraftforge/gradle/userdev/tasks/ApplyMCPFunction.java#L76
Which want touched in the commit you linked.

However, it may be caused by the other crap that is exploding higher up the stack.
Can't reproduce as I don't use Intellij so you'll need someone else for this.

**Comment by JTK222** [comment]
Hm.. I continued testing and noticed that after downgrading to FG 3.0.184 first, I can properly upgrade to 3.0.185 without issues.
That's extremely confusing, because I had the same issue on another computer with a different project.
Sadly I can't test it on that machine till Monday.

But as it seems doing this process on one project fixed it for all my other projects too.
This might just be a caching issues on IntelliJs Site. But as said I am not knowledgeable enough about that topic.
If you feel that this is probably just a caching issue feel free to close this.
Otherwise I'll try this again on Monday on the other machine that had this issue.

**Comment by DaemonUmbra** [comment]
This error is a result of ForgeGradle not being friendly with the Gradle daemon and intellij's entire Gradle integration being based on the daemon.

Run ``gradlew --stop`` to stop the daemon then try again.

To be honest this is a known issue, but we can't be arsed to put in the effort to track this one through Gradle's spaghetti internals when the workaround is so simple.
