### ISSUE TITLE
ForgeGradle add library even if Downloads.artifact is null

### ISSUE THREAD

**Issue by anatawa12** [MinecraftForge/ForgeGradle#769]
Relates #627
This issue cause problem currently if targeting 1.12.2 but I think this is a general issue so I report this.

In 1.12.2.json, there's a library without downloads.artifact, only with downloads.classifiers. ("org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822")
Because the library without a classifier does not exist at the server, I think it's only for libraries with a classifier.
So I think ForgeGradle should not add the libraries without downloads.artifact to a pom.

I fixed this issue in [my fork](https://github.com/anatawa12/ForgeGradle) and tested it with my project, it looks to work well with 1.12.2-14.23.5.2855.

**Comment by ravenbuilder934** [comment]
does it also happen on modern versions?

**Comment by anatawa12** [comment]
I don't know because I'm developing 1.12.2 or 1.7.10

**Comment by LexManos** [comment]
Typically we expect things to be tested on modern versions. 
Old versions are out of support, so we usually like to see any bug reports specifically for those versions to include tests cases and a PR.
Or at least actually show that your issue is real so we don't have to dig around. But yes it appears the [1.12.2.json](https://launchermeta.mojang.com/v1/packages/6e69e85d0f85f4f4b9e12dd99d102092a6e15918/1.12.2.json) has the natives for lwjgl-platform, and jinput-platform, with no main jar.
This is not an issue with [modern jsons](https://launchermeta.mojang.com/v1/packages/436877ffaef948954053e1a78a366b8b7c204a91/1.16.5.json)

The fix would be simple yes. Also reminds me that the code should probably be deduplicated as it's in multiple repos.
