### ISSUE TITLE
[FG5.1] fg.deobf(...) does not seem to work with Java 16

### ISSUE THREAD

**Issue by SuperMartijn642** [MinecraftForge/ForgeGradle#813]
### Versions:
- Minecraft Version: 1.17.1
- Forge Version: 37.0.1
- Forge Gradle 5.1

### Issue:
With FG5, `fg.deobf` doesn't seem to work on jars compiled with Java 16. Jars compiled with Java 8 work fine. This means any mods compiled for 1.17 currently don't work with `fg.deobf`.
It gives the error 'Unsupported class file major version 60'.

#### Gradle log: https://gist.github.com/SuperMartijn642/9e7cba68b8eba27afe8b2898b39330dd

**Comment by sciwhiz12** [comment]
It seems that the InstallerTools version [is still `1.1.10`](https://github.com/MinecraftForge/ForgeGradle/blob/b170e2e4b39607e5ab98aad92a17c13fc457fcc2/src/common/java/net/minecraftforge/gradle/common/util/Utils.java#L100), even though the latest version is `1.2.7`, with the version that first supports Java 16 (due to the ASM bump) being `1.2.4`.

**Comment by SizableShrimp** [comment]
Fixed in 8ead65a2a4c5a2bdcdd05f2c1ce3df492e7345c6
